/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VppCallableObjectArgs1 struct {
	State string `json:"state"`
	Addr string `json:"addr"`
	HostIfname string `json:"host_ifname"`
	Ifname string `json:"ifname"`
}
