/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialTunnelObject_ struct {
	TunnelId float64 `json:"tunnel_id,omitempty"`
	ServerSrcId float64 `json:"server_src_id,omitempty"`
	ServerDstId float64 `json:"server_dst_id,omitempty"`
	InterfaceSrcId float64 `json:"interface_src_id,omitempty"`
	TunnelCidrIpv6 string `json:"tunnel_cidr_ipv6,omitempty"`
	TunnelStatus *Status `json:"tunnel_status,omitempty"`
	TunnelStatusReason string `json:"tunnel_status_reason,omitempty"`
}
