/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgentMessageType string

// List of AgentMessageType
const (
	AUTO_PING_AgentMessageType AgentMessageType = "AUTO_PING"
	EXEC_AgentMessageType AgentMessageType = "EXEC"
	GET_INFO_AgentMessageType AgentMessageType = "GET_INFO"
	IPCONF_AgentMessageType AgentMessageType = "IPCONF"
	LOGGER_AgentMessageType AgentMessageType = "LOGGER"
	MONITORING_AgentMessageType AgentMessageType = "MONITORING"
	NATCONF_AgentMessageType AgentMessageType = "NATCONF"
	NFTABLES_AgentMessageType AgentMessageType = "NFTABLES"
	PING_AgentMessageType AgentMessageType = "PING"
	QUEUE_AgentMessageType AgentMessageType = "QUEUE"
	RESTART_WG_AgentMessageType AgentMessageType = "RESTART_WG"
	SPEEDTEST_AgentMessageType AgentMessageType = "SPEEDTEST"
	SRCONF_AgentMessageType AgentMessageType = "SRCONF"
	VPNCONF_AgentMessageType AgentMessageType = "VPNCONF"
	VPPCONF_AgentMessageType AgentMessageType = "VPPCONF"
	VPPCONF_V2_AgentMessageType AgentMessageType = "VPPCONF_V2"
)
