/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type NetworkGenesisType string

// List of NetworkGenesisType
const (
	UI_NetworkGenesisType NetworkGenesisType = "UI"
	SDK_NetworkGenesisType NetworkGenesisType = "SDK"
	CONFIG_NetworkGenesisType NetworkGenesisType = "CONFIG"
)
