/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialContentObject_ struct {
	ContentTitle string `json:"content_title,omitempty"`
	ContentKey string `json:"content_key,omitempty"`
	ContentBody string `json:"content_body,omitempty"`
	LangId float64 `json:"lang_id,omitempty"`
	ContentType *ContextType `json:"content_type,omitempty"`
	ContentVisibility *VisibilityType `json:"content_visibility,omitempty"`
}
