/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WgAddPeerArgs struct {
	EndpointPort float64 `json:"endpoint_port"`
	EndpointIpv4 string `json:"endpoint_ipv4"`
	AllowedIps []string `json:"allowed_ips"`
	PublicKey string `json:"public_key"`
	Ifname string `json:"ifname"`
	GwIpv4 string `json:"gw_ipv4"`
}
