/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WgCreateInterfaceArgs struct {
	PublicKey string `json:"public_key,omitempty"`
	ListenPort float64 `json:"listen_port,omitempty"`
	InternalIp string `json:"internal_ip"`
	Ifname string `json:"ifname"`
}
