/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VppCallableObjectArgs6 struct {
	Enable bool `json:"enable,omitempty"`
	PortRange string `json:"port_range,omitempty"`
	Addr string `json:"addr"`
	Ifname string `json:"ifname"`
}
