/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VppCallableObjectArgs5 struct {
	ExtAddr string `json:"ext_addr"`
	LocalAddr string `json:"local_addr"`
	Ifname string `json:"ifname"`
}
