/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BiStatisticsEdgesPost struct {
	TimeWindow float64 `json:"timeWindow"`
	SuccessfulRequestsCount float64 `json:"successfulRequestsCount"`
	ErroneousRequestsCount float64 `json:"erroneousRequestsCount"`
	RequestsCount float64 `json:"requestsCount"`
	PendingRequestsCount float64 `json:"pendingRequestsCount"`
}
