/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerSrSoftware string

// List of ServerSrSoftware
const (
	NONE_ServerSrSoftware ServerSrSoftware = "NONE"
	VPP_ServerSrSoftware ServerSrSoftware = "VPP"
	SREXT_ServerSrSoftware ServerSrSoftware = "SREXT"
)
