/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UserSrDirection string

// List of UserSrDirection
const (
	NOT_SPECIFIED_UserSrDirection UserSrDirection = "NOT_SPECIFIED"
	FORWARD_UserSrDirection UserSrDirection = "FORWARD"
	BACKWARD_UserSrDirection UserSrDirection = "BACKWARD"
)
