/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialUserSrObject_ struct {
	UserId float64 `json:"user_id,omitempty"`
	RegionId float64 `json:"region_id,omitempty"`
	UserSrLocationLat float64 `json:"user_sr_location_lat,omitempty"`
	UserSrLocationLon float64 `json:"user_sr_location_lon,omitempty"`
	UserSrLocationCity string `json:"user_sr_location_city,omitempty"`
	ColorId float64 `json:"color_id,omitempty"`
	BandwidthMin float64 `json:"bandwidth_min,omitempty"`
	JitterMax float64 `json:"jitter_max,omitempty"`
	LatencyMax float64 `json:"latency_max,omitempty"`
	PriceMax float64 `json:"price_max,omitempty"`
	UserIpv4SourceAddr string `json:"user_ipv4_source_addr,omitempty"`
	UserIpv6SourceAddr string `json:"user_ipv6_source_addr,omitempty"`
	UserIpv4DestAddr string `json:"user_ipv4_dest_addr,omitempty"`
	UserIpv6DestAddr string `json:"user_ipv6_dest_addr,omitempty"`
	UserIpv4DestCidr string `json:"user_ipv4_dest_cidr,omitempty"`
	UserIpv6DestCidr string `json:"user_ipv6_dest_cidr,omitempty"`
	ServerVpnId float64 `json:"server_vpn_id,omitempty"`
	ServerVinId float64 `json:"server_vin_id,omitempty"`
	ServerVenId float64 `json:"server_ven_id,omitempty"`
	SrPolicyId float64 `json:"sr_policy_id,omitempty"`
	UserSrDirection *UserSrDirection `json:"user_sr_direction,omitempty"`
	UserSrStatus *Status `json:"user_sr_status,omitempty"`
	UserSrStatusReason string `json:"user_sr_status_reason,omitempty"`
	// Indicates if current configuration routes traffic via SDN.
	UserSrIsViaSdn bool `json:"user_sr_is_via_sdn,omitempty"`
}
