/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VppCallableObjectArgs9 struct {
	DstAddr string `json:"dst_addr"`
	SrcAddr string `json:"src_addr"`
	Ifname string `json:"ifname"`
}
