/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LinkTag string

// List of LinkTag
const (
	PUBLIC_LinkTag LinkTag = "PUBLIC"
	SDN1_LinkTag LinkTag = "SDN1"
	SDN2_LinkTag LinkTag = "SDN2"
	SDN3_LinkTag LinkTag = "SDN3"
)
