/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialApiKeyObject_ struct {
	UserId float64 `json:"user_id,omitempty"`
	ApiKeySecret string `json:"api_key_secret,omitempty"`
	ApiKeyName string `json:"api_key_name,omitempty"`
	ApiKeyValidUntil string `json:"api_key_valid_until,omitempty"`
}
