/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type BehaviorType string

// List of BehaviorType
const (
	END_BehaviorType BehaviorType = "end"
	ENDX_BehaviorType BehaviorType = "end.x"
	ENDT_BehaviorType BehaviorType = "end.t"
	ENDDX2_BehaviorType BehaviorType = "end.dx2"
	ENDDX6_BehaviorType BehaviorType = "end.dx6"
	ENDDX4_BehaviorType BehaviorType = "end.dx4"
	ENDDT6_BehaviorType BehaviorType = "end.dt6"
	ENDDT4_BehaviorType BehaviorType = "end.dt4"
	ENDMASQ_BehaviorType BehaviorType = "end.masq"
)
