/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type SettingsTypes string

// List of SettingsTypes
const (
	INTEGER_SettingsTypes SettingsTypes = "INTEGER"
	SERIALIZED_STRINGS_SettingsTypes SettingsTypes = "SERIALIZED_STRINGS"
)
