/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TsoaPartialAgentObject_ struct {
	AgentServicesDefaultStatus bool `json:"agent_services_default_status,omitempty"`
	ApiKeyId float64 `json:"api_key_id,omitempty"`
	AgentPublicIpv4 string `json:"agent_public_ipv4,omitempty"`
	AgentLocationLat float64 `json:"agent_location_lat,omitempty"`
	AgentLocationLon float64 `json:"agent_location_lon,omitempty"`
	AgentLocationCity string `json:"agent_location_city,omitempty"`
	AgentLocationCountry string `json:"agent_location_country,omitempty"`
	AgentDeviceId string `json:"agent_device_id,omitempty"`
	AgentName string `json:"agent_name,omitempty"`
	AgentStatus *PlatformAgentStatus `json:"agent_status,omitempty"`
	AgentVersion string `json:"agent_version,omitempty"`
	AgentProviderId float64 `json:"agent_provider_id,omitempty"`
	AgentIsOnline bool `json:"agent_is_online,omitempty"`
	AgentLockedFields *ModelMap `json:"agent_locked_fields,omitempty"`
	AgentModifiedAt time.Time `json:"agent_modified_at,omitempty"`
	AgentIsVirtual bool `json:"agent_is_virtual,omitempty"`
	AgentType *PlatformAgentTypeLocal `json:"agent_type,omitempty"`
}
