/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type PlatformAgentsHitObjectSource struct {
	AgentId float64 `json:"agent_id"`
	Severity string `json:"severity"`
	Timestamp time.Time `json:"@timestamp"`
}
