/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WgAddPeerMetadataAllowedIpsInfo struct {
	AgentServiceSubnetIp string `json:"agent_service_subnet_ip"`
	AgentServiceUdpPorts []float64 `json:"agent_service_udp_ports"`
	AgentServiceTcpPorts []float64 `json:"agent_service_tcp_ports"`
	AgentServiceName string `json:"agent_service_name"`
}
