/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialAgentInterfaceObject_ struct {
	AgentId float64 `json:"agent_id,omitempty"`
	UserId float64 `json:"user_id,omitempty"`
	AgentInterfaceIsConfigured bool `json:"agent_interface_is_configured,omitempty"`
	AgentInterfaceLinkTag *LinkTag `json:"agent_interface_link_tag,omitempty"`
	AgentInterfaceName string `json:"agent_interface_name,omitempty"`
	AgentInterfacePublicKey string `json:"agent_interface_public_key,omitempty"`
	AgentInterfaceEndpointIpv4 string `json:"agent_interface_endpoint_ipv4,omitempty"`
	AgentInterfaceEndpointPort float64 `json:"agent_interface_endpoint_port,omitempty"`
	AgentInterfaceInternalIpv4 string `json:"agent_interface_internal_ipv4,omitempty"`
}
