/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VppCallableObjectArgs10 struct {
	HostBridge string `json:"host_bridge,omitempty"`
	HostIp4Addr string `json:"host_ip4_addr"`
	Addr string `json:"addr"`
}
