/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialAgentProviderObject_ struct {
	AgentProviderName string `json:"agent_provider_name,omitempty"`
	AgentProviderIconUrl string `json:"agent_provider_icon_url,omitempty"`
}
