/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialVpnObject_ struct {
	IngressServerId float64 `json:"ingress_server_id,omitempty"`
	VpnInternalIpv4 string `json:"vpn_internal_ipv4,omitempty"`
	VpnPublicKey string `json:"vpn_public_key,omitempty"`
	VpnEndpointIp string `json:"vpn_endpoint_ip,omitempty"`
	VpnGatewayIpv4 string `json:"vpn_gateway_ipv4,omitempty"`
	VpnInterfaceIp string `json:"vpn_interface_ip,omitempty"`
}
