/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ConstraintEnum string

// List of ConstraintEnum
const (
	HIGH_ConstraintEnum ConstraintEnum = "HIGH"
	MID_ConstraintEnum ConstraintEnum = "MID"
	LOW_ConstraintEnum ConstraintEnum = "LOW"
	ANY_ConstraintEnum ConstraintEnum = "ANY"
)
