/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlatformAgentTypeLocal string

// List of PlatformAgentTypeLocal
const (
	LINUX_PlatformAgentTypeLocal PlatformAgentTypeLocal = "Linux"
	MAC_OS_PlatformAgentTypeLocal PlatformAgentTypeLocal = "macOS"
	WINDOWS_PlatformAgentTypeLocal PlatformAgentTypeLocal = "Windows"
	VIRTUAL_PlatformAgentTypeLocal PlatformAgentTypeLocal = "Virtual"
)
