/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialVersionObject_ struct {
	VersionType *VersionType `json:"version_type,omitempty"`
	VersionCurrent string `json:"version_current,omitempty"`
}
