/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialProviderObject_ struct {
	ProviderName string `json:"provider_name,omitempty"`
	ProviderTunnelsRequired bool `json:"provider_tunnels_required,omitempty"`
}
