/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type LogsReadTimestampEntityTypes string

// List of LogsReadTimestampEntityTypes
const (
	AGENT_ERROR_LogsReadTimestampEntityTypes LogsReadTimestampEntityTypes = "AGENT_ERROR"
	CONNECTION_ERROR_LogsReadTimestampEntityTypes LogsReadTimestampEntityTypes = "CONNECTION_ERROR"
	AGENT_WARNING_LogsReadTimestampEntityTypes LogsReadTimestampEntityTypes = "AGENT_WARNING"
	CONNECTION_WARNING_LogsReadTimestampEntityTypes LogsReadTimestampEntityTypes = "CONNECTION_WARNING"
)
