/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServerAgentStatus string

// List of ServerAgentStatus
const (
	OFFLINE_ServerAgentStatus ServerAgentStatus = "OFFLINE"
	ONLINE_ServerAgentStatus ServerAgentStatus = "ONLINE"
)
