/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialAgentNetworkObject_ struct {
	AgentId float64 `json:"agent_id,omitempty"`
	AgentNetworkIdExternal string `json:"agent_network_id_external,omitempty"`
	AgentNetworkName string `json:"agent_network_name,omitempty"`
	AgentNetworkSubnet string `json:"agent_network_subnet,omitempty"`
}
