/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialTranslationObject_ struct {
	LangId float64 `json:"lang_id,omitempty"`
	TranslationKey string `json:"translation_key,omitempty"`
	TranslationValue string `json:"translation_value,omitempty"`
	TranslationType *ContextType `json:"translation_type,omitempty"`
	TranslationVisibility *VisibilityType `json:"translation_visibility,omitempty"`
}
