/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WgRemovePeerArgs struct {
	AllowedIps []string `json:"allowed_ips"`
	PublicKey string `json:"public_key"`
	Ifname string `json:"ifname"`
}
