/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPickAgentAgentNameOrAgentId_ struct {
	AgentId float64 `json:"agent_id"`
	AgentName string `json:"agent_name"`
}
