/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type AgentServiceTypes string

// List of AgentServiceTypes
const (
	DOCKER_AgentServiceTypes AgentServiceTypes = "DOCKER"
	HOST_AgentServiceTypes AgentServiceTypes = "HOST"
	KUBERNETES_AgentServiceTypes AgentServiceTypes = "KUBERNETES"
	MANUAL_AgentServiceTypes AgentServiceTypes = "MANUAL"
)
