/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type VersionType string

// List of VersionType
const (
	APP_LINUX_VersionType VersionType = "APP_LINUX"
	APP_WINDOWS_VersionType VersionType = "APP_WINDOWS"
	APP_MAC_VersionType VersionType = "APP_MAC"
	APP_IOS_VersionType VersionType = "APP_IOS"
	APP_ANDROID_VersionType VersionType = "APP_ANDROID"
	LANGUAGES_VersionType VersionType = "LANGUAGES"
	CONTENT_VersionType VersionType = "CONTENT"
	TRANSLATIONS_VersionType VersionType = "TRANSLATIONS"
	LINKS_VersionType VersionType = "LINKS"
)
