/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WgAddPeerMetadata struct {
	AllowedIpsInfo []WgAddPeerMetadataAllowedIpsInfo `json:"allowed_ips_info"`
	LinkTag *LinkTag `json:"link_tag"`
	AgentId float64 `json:"agent_id"`
	ConnectionId float64 `json:"connection_id"`
	DevicePublicIpv4 string `json:"device_public_ipv4"`
	DeviceName string `json:"device_name"`
	DeviceId string `json:"device_id"`
}
