/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialLinkObject_ struct {
	LangId float64 `json:"lang_id,omitempty"`
	LinkWeight float64 `json:"link_weight,omitempty"`
	LinkTitle string `json:"link_title,omitempty"`
	LinkUrl string `json:"link_url,omitempty"`
	LinkType *ContextType `json:"link_type,omitempty"`
	LinkImgUrl string `json:"link_img_url,omitempty"`
	LinkVisibility *VisibilityType `json:"link_visibility,omitempty"`
}
