/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InterfaceType string

// List of InterfaceType
const (
	EXTERNAL_InterfaceType InterfaceType = "EXTERNAL"
	INTERNAL_InterfaceType InterfaceType = "INTERNAL"
)
