/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlatformResponseErrorItem struct {
	Value *AnyOfPlatformResponseErrorItemValue `json:"value,omitempty"`
	Message string `json:"message,omitempty"`
	Property string `json:"property,omitempty"`
	Name string `json:"name,omitempty"`
}
