/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger
import (
	"time"
)

type TsoaPartialAgentConnectionObject_ struct {
	Agent1Id float64 `json:"agent_1_id,omitempty"`
	AgentInterface1Id float64 `json:"agent_interface_1_id,omitempty"`
	Agent2Id float64 `json:"agent_2_id,omitempty"`
	AgentInterface2Id float64 `json:"agent_interface_2_id,omitempty"`
	UserId float64 `json:"user_id,omitempty"`
	AgentSdnPolicyId float64 `json:"agent_sdn_policy_id,omitempty"`
	AgentConnectionLinkTag *LinkTag `json:"agent_connection_link_tag,omitempty"`
	AgentConnectionStatus *AgentConnectionStatus `json:"agent_connection_status,omitempty"`
	AgentConnectionLastHandshake time.Time `json:"agent_connection_last_handshake,omitempty"`
	AgentConnectionTxBytesTotal float64 `json:"agent_connection_tx_bytes_total,omitempty"`
	AgentConnectionRxBytesTotal float64 `json:"agent_connection_rx_bytes_total,omitempty"`
	AgentConnectionLatencyMs float64 `json:"agent_connection_latency_ms,omitempty"`
	AgentConnectionPacketLoss float64 `json:"agent_connection_packet_loss,omitempty"`
}
