/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialAgentPathObject_ struct {
	AgentInterfaceId float64 `json:"agent_interface_id,omitempty"`
	AgentId float64 `json:"agent_id,omitempty"`
	AgentConnectionId float64 `json:"agent_connection_id,omitempty"`
}
