/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ShowSdnConnections string

// List of ShowSdnConnections
const (
	NO_ShowSdnConnections ShowSdnConnections = "NO"
	YES_ShowSdnConnections ShowSdnConnections = "YES"
)
