/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialNetworkObject_ struct {
	UserId float64 `json:"user_id,omitempty"`
	NetworkKey string `json:"network_key,omitempty"`
	NetworkName string `json:"network_name,omitempty"`
	NetworkMetadata *ModelMap `json:"network_metadata,omitempty"`
}
