/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type TsoaPartialAgentInterfaceBwObject_ struct {
	AgentInterfaceId float64 `json:"agent_interface_id,omitempty"`
	AgentInterfaceBwRxSpeedMbps float64 `json:"agent_interface_bw_rx_speed_mbps,omitempty"`
	AgentInterfaceBwTxSpeedMbps float64 `json:"agent_interface_bw_tx_speed_mbps,omitempty"`
	AgentInterfaceBwTxDropped float64 `json:"agent_interface_bw_tx_dropped,omitempty"`
	AgentInterfaceBwRxDropped float64 `json:"agent_interface_bw_rx_dropped,omitempty"`
	AgentInterfaceBwTxErrors float64 `json:"agent_interface_bw_tx_errors,omitempty"`
	AgentInterfaceBwRxErrors float64 `json:"agent_interface_bw_rx_errors,omitempty"`
	AgentInterfaceBwTxPackets float64 `json:"agent_interface_bw_tx_packets,omitempty"`
	AgentInterfaceBwRxPackets float64 `json:"agent_interface_bw_rx_packets,omitempty"`
}
