/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Status string

// List of Status
const (
	NEW_Status Status = "NEW"
	NOT_PROCESSED_Status Status = "NOT_PROCESSED"
	PROCESS_Status Status = "PROCESS"
	NOT_CONFIGURED_Status Status = "NOT_CONFIGURED"
	CONFIGURE_Status Status = "CONFIGURE"
	CONFIGURED_Status Status = "CONFIGURED"
	UNCONFIGURE_Status Status = "UNCONFIGURE"
	RECONFIGURE_Status Status = "RECONFIGURE"
	TEST_Status Status = "TEST"
	READY_Status Status = "READY"
	PROCESS_ERROR_Status Status = "PROCESS_ERROR"
	CONFIGURATION_ERROR_Status Status = "CONFIGURATION_ERROR"
	UNCONFIGURATION_ERROR_Status Status = "UNCONFIGURATION_ERROR"
	NO_OPERATION_Status Status = "NO_OPERATION"
)
