/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type PlatformAgentStatus string

// List of PlatformAgentStatus
const (
	OK_PlatformAgentStatus PlatformAgentStatus = "OK"
	WG_ERROR_PlatformAgentStatus PlatformAgentStatus = "WG_ERROR"
	DUPLICATE_NAME_ERROR_PlatformAgentStatus PlatformAgentStatus = "DUPLICATE_NAME_ERROR"
)
