/*
 * syntropy-controller
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 0.1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MetadataNetworkType string

// List of MetadataNetworkType
const (
	P2_P_MetadataNetworkType MetadataNetworkType = "P2P"
	P2_M_MetadataNetworkType MetadataNetworkType = "P2M"
	MESH_MetadataNetworkType MetadataNetworkType = "MESH"
)
